name: 'Slack Notifications on GitHub Actions'
description: 'Notify Slack channel on GitHub Actions'
branding:
  icon: 'bell'
  color: 'green'

inputs:
  action-status:
    description: 'Status of the action. Can be Success, Failure'
    required: true
    default: 'Success'
  slack-web-hook:
    description: 'Slack WebHook URL'
    required: true
    default: "null"
  slack-channel-name:
    description: 'Slack channel name'
    required: true
    default: "null"
  title:
    description: 'Title of the message'
    required: true
    default: "Post Title"
  message:
    description: 'Message'
    required: true
    default: "Post Content :rocket:"

runs:
  using: "composite"
  steps:
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: ${{ inputs.slack-channel-name }}
        SLACK_COLOR: ${{ inputs.action-status }}
        SLACK_ICON: '' # add your slack icon
        SLACK_MESSAGE: ${{ inputs.message }}
        SLACK_TITLE: ${{ inputs.title }}
        SLACK_USERNAME: GitHubBot
        SLACK_WEBHOOK: ${{ inputs.slack-web-hook }}
        MSG_MINIMAL: event,actions url,commit
